const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const packageJsonPath = path.join(__dirname, '../package.json');
const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

// Builds pass --bump: the version becomes <year>.<month>.<day>-build.<n>,
// counting up within a day, the same scheme as the other web products.
// `npm start` doesn't bump, so local serves leave package.json alone.
if (process.argv.includes('--bump')) {
  const now = new Date();
  const today = `${now.getFullYear()}.${now.getMonth() + 1}.${now.getDate()}`;
  const match = String(pkg.version).match(/^(\d+\.\d+\.\d+)-build\.(\d+)$/);
  pkg.version = `${today}-build.${match && match[1] === today ? Number(match[2]) + 1 : 1}`;
  fs.writeFileSync(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`);
}

let gitSha = 'unknown';
try {
  gitSha = execSync('git rev-parse --short HEAD', { cwd: __dirname }).toString().trim();
} catch {
  // no git repo available (e.g. some CI checkouts) — fall back to 'unknown'
}

const content = `// Auto-generated by scripts/generate-version.js at build time. Do not edit.
export const BUILD_VERSION = {
  version: '${pkg.version}',
  gitSha: '${gitSha}',
  buildTime: '${new Date().toISOString()}',
};
`;

fs.writeFileSync(path.join(__dirname, '../src/app/version.ts'), content);
console.log(`Generated src/app/version.ts (v${pkg.version} @ ${gitSha})`);
